image: gitpod/workspace-full-vnc

tasks:
  - command: |
      cd /workspace
      wget https://github.com/wtsi-hpag/PretextView/releases/download/0.2.5/PretextView_Linux-x86-64.zip
      unzip PretextView_Linux-x86-64.zip

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
